version: "3.10"

services:
  studysite:
    restart: always
    build:
      context: ./studysite # django service folder
    image: studysite

  postgresql-db:
    restart: always
    image: postgres
    env_file: ./postgresql-db/.pg-env

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"